apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  namespace: dev
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: ameertabri/polybot-dev:80
          ports:
            - containerPort: 3000
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: polybot-secret
                  key: TELEGRAM_BOT_TOKEN
            - name: BOT_APP_URL
              value: "https://ameer-bot-dev.fursa.click"
---
apiVersion: v1
kind: Service
metadata:
  name: service-polybot
  namespace: dev
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polybot-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ameer-bot-dev.fursa.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-polybot
                port:
                  number: 8443
