apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
      labels:
        app: polybot
    spec:
      containers:
        - name: polybot
          image: ameertabri/polybot-dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: polybot
spec:
  type: NodePort
  selector:
    app: polybot
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32222
