apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: prod
  labels:
    app: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: ameertabri/yolo-dev:30
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-yolo
  namespace: prod
spec:
  selector:
    app: yolo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
