name: Deploy Nginx (Dev)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy config and certs
        run: |
          scp -o StrictHostKeyChecking=no -r nginx-config/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/conf.d/
          if [ -d certs ]; then
            scp -o StrictHostKeyChecking=no -r certs/* ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/certs/
          fi
          scp -o StrictHostKeyChecking=no deploy_nginx.sh ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Deploy NGINX container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            bash /home/ubuntu/deploy_nginx.sh
          EOF
